<?php
$con = new mysqli("localhost","root","","mydatabase");
if($con->connect_errno)
{
    echo "<p>There is some issue related to this connection";
    echo "<br> The error message generated by system is:".$con->connect-error;
    echo "<br>the error number generated by the system is :".$con->connect_errno;
    exit();
}
else
{
    echo"Connected successfully";
}
?>